version: '3'
services:
  api:
    container_name: node_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=develop
    depends_on:
          - "db"
    links:
          - "db:mongodb"

  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"